### 1. Platform: Hello Check
GET {{protocol}}://{{host}}/v1/hello
Accept: application/json

### 2. Platform: Health Check
GET {{protocol}}://{{host}}/actuator/health
Accept: application/json

### 3. Platform: Swagger UI
GET {{protocol}}://{{host}}/swagger-ui.html

### 4. Platform: API Docs (JSON)
GET {{protocol}}://{{host}}/api-docs
Accept: application/json
