### 1. Register Customer
POST {{protocol}}://{{host}}{{apiPrefix}}/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password123!",
  "fullName": "Gaya User"
}

### 2. Login Customer
POST {{protocol}}://{{host}}{{apiPrefix}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "Password123!"
}

> {% client.global.set("accessToken", response.body.data.tokens.accessToken); %}
> {% client.global.set("refreshToken", response.body.data.tokens.refreshToken); %}

### 3. Get Current Profile
GET {{protocol}}://{{host}}{{apiPrefix}}/me
Authorization: Bearer {{accessToken}}
Accept: application/json

### 4. Refresh Token
POST {{protocol}}://{{host}}{{apiPrefix}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}
