### 1. Register Customer
POST {{protocol}}://{{host}}/v1/auth/register
Content-Type: application/json

{
  "email": "user_{{$randomInt}}@example.com",
  "password": "Password123!",
  "fullName": "Gaya User",
  "phone": "08123456789"
}

### 2. Login as Customer (Seed)
POST {{protocol}}://{{host}}/v1/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password"
}

> {% client.global.set("customerToken", response.body.data.tokens.accessToken); client.global.set("customerRefreshToken", response.body.data.tokens.refreshToken); %}

### 3. Login as Admin (Seed)
POST {{protocol}}://{{host}}/v1/auth/login
Content-Type: application/json

{
  "email": "admin@gayakini.com",
  "password": "password"
}

> {% client.global.set("adminToken", response.body.data.tokens.accessToken); %}

### 4. Verify Customer Token
GET {{protocol}}://{{host}}/v1/me
Authorization: Bearer {{customerToken}}
Accept: application/json

### 5. Refresh Token
POST {{protocol}}://{{host}}/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{customerRefreshToken}}"
}
