### 1. List Products
GET {{protocol}}://{{host}}{{apiPrefix}}/products?page=0&size=10
Accept: application/json

### 2. Search Products
GET {{protocol}}://{{host}}{{apiPrefix}}/products?q=t-shirt
Accept: application/json

### 3. Get Product Detail
# Use a valid UUID from the list products results
GET {{protocol}}://{{host}}{{apiPrefix}}/products/{{productId}}
Accept: application/json
