### 1. List Products
GET {{protocol}}://{{host}}/v1/products?page=1&size=10
Accept: application/json

### 2. Get Product Detail
# Replace dengan UUID produk aktual dari hasil list
GET {{protocol}}://{{host}}/v1/products/REPLACE_WITH_PRODUCT_ID
Accept: application/json

### 3. Search Products
GET {{protocol}}://{{host}}/v1/products?q=t-shirt
Accept: application/json
