### 1. Place Order from Checkout
POST {{protocol}}://{{host}}/v1/checkouts/{{checkoutId}}/orders
Content-Type: application/json
Idempotency-Key: {{requestId}}
X-Checkout-Token: {{checkoutToken}}

{
  "customerNotes": "Please handle with care."
}

> {% client.global.set("orderId", response.body.data.id); %}
> {% client.global.set("orderToken", response.body.data.accessToken); %}

### 2. Get Order Detail
GET {{protocol}}://{{host}}/v1/orders/{{orderId}}
Accept: application/json
X-Order-Token: {{orderToken}}

### 3. Create Payment Session
POST {{protocol}}://{{host}}/v1/orders/{{orderId}}/payments
Content-Type: application/json
Idempotency-Key: {{requestId}}
X-Order-Token: {{orderToken}}

{}

### 4. List My Orders (Authorized)
GET {{protocol}}://{{host}}/v1/me/orders
Authorization: Bearer {{accessToken}}
Accept: application/json
