### 1. Hello Check
GET {{protocol}}://{{host}}/v1/hello
Accept: application/json

### 2. Health Check
GET {{protocol}}://{{host}}/actuator/health
Accept: application/json

### 3. Product Browsing
GET {{protocol}}://{{host}}/v1/products
Accept: application/json
